### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by stefanbethke** [joshbeard/puppet-crowd#22]
There's been quite a few commits since the last release in 2016. Any chance you could release soon?

**Comment by vidkun** [comment]
Is this module still maintained?

**Comment by ojongerius** [comment]
@joshbeard are you looking for volunteers to help out with this? -I'm not proposing to volunteer but others might be keen

**Comment by joshbeard** [comment]
I'm very sorry for the dormancy. I haven't been actively maintaining the module myself, but I am using it myself in production. I will publish a new release from the current master.

The module is a bit stale, indeed. I'm interested in requesting a transfer of ownership to the 'puppet' group and will look into that, but I am happy for any assistance otherwise.

**Comment by joshbeard** [comment]
Hi, 1.1.0 was published to the Puppet Forge today with a number of changes:

https://forge.puppet.com/joshbeard/crowd/1.1.0/changelog
